### ISSUE TITLE
Add 3 Real Agencies

### ISSUE THREAD

**Issue by blandfordc** [blandfordc/CSCI380#3]
Rather than the testing agencies that we have right now, hardcode 3 real agencies (Talbert House, Addiction Services Council, and CATT).

**Comment by josephthompson33** [comment]
we should just read stuff in using this: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.Java.02.html
we already have the json, it shouldn't be all that hard barring some technology barrier
